sudo: required
dist: bionic
language: cpp
matrix:
  include:
  - os: osx
    env: TARGET=darwin
  - os: linux
    env: TARGET=linux_x86_64
  - os: linux
    env: TARGET=linux_i686
  - os: linux
    env: TARGET=linux_armv7l
  - os: linux
    env: TARGET=linux_aarch64
  - os: linux
    env: TARGET=windows_x86
  - os: linux
    env: TARGET=windows_amd64
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TARGET" == "linux_i686" ]]; then sudo dpkg --add-architecture i386; fi
- if [[ "$TARGET" == "linux_armv7l" ]]; then sudo dpkg --add-architecture armhf; fi
- if [[ "$TARGET" == "linux_aarch64" ]]; then sudo dpkg --add-architecture arm64; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
- if [[ "$TRAVIS_OS_NAME" == "darwin" ]]; then echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile && source ~/.bash_profile; fi
script:
- bash build.sh $TARGET
- openssl sha1 _packages/**/*.tar.gz
deploy:
  provider: releases
  api_key:
    secure: Pk/7TQkwbXfsn2XYP6kvPMvWTVBDC/4l/QTSdSHg4O8aZqWM74/U3lz2NIdJadfXmd5ygEgBGFZJihN3OgEY1xeKJoFamZttS5oPudR5jfnnUG1gCaizOZ7k7GHuSnNCJR/MUUqjfB8CPXD8j/2R/CPvWW50/pLmymCBrs/WsT7PUWPMK1JCZYIrcDkFm6c7HqRLxwcG3kKE4Nm/7IDJFG5DaLSJu6WLLmf7C2SzKBPs4jyN7rvla7WxeaE+XHIExaLm7bRe6X9BU/F8Ken5zo/aVwiQM05/CEPkFyQOddWhZtjo2E+Hvpx9r511+G38yHplhjJWdwUjt4W4ZW2eHaYyHvLDokDb0UgfmNWaLWEjLzNmF0SOUgtKywE5Zcre9eU9hn2XqpEo5aW650mmc56SKUoaw+PiF39B1oiBBXAEzWyXRhqEpiZ1y3H13A9o1f7CfP09IErtC7Yn6geN0+eMYqaV2/AP3vuFHz+DvQeczQZiHB/Nh4OcKoF5oGtQJN1Wtxr1jobOz3q3IADEx2B3F4SCBxnTJ0soVK6on0OMHNVn+uA4pSvRcYrZAL7lKRB/VWTvOsmQxKXzBEX9PSZRL5ygI1Aud0m8Juzao5Nl3nhzKp+hKLbP//5Zcuiur8leA+l2wt9mVd/NRDXE/EIWej1gMYOWAkwpzcJUQ8U=
  file: _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: elutow/toolchain-icestorm
    tags: true
